int length(char* string);
int compare(char* string1, char* string2);
void array_input_keyboard(int* numbers, int size);
void array_input_random(int* numbers, int size);
int array_min(int* array, int size);
void array_output(int* array, int size);
void array_memory(int** array, int* sizeofarray, int min);
void array_start_memory(int** array, int sizeofarray);
void array_choice(char* choice, char* check_k, char* check_r);
void array_size(int* amountofrows);
void choice_compare(int* array, char* choice, char* check_k, int sizeofarray);
void size_check(int sizeofarray);
void array_free(int** array);